name: deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@dev
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: vim-kr/vim-kr.github.io
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: yarn install && yarn build
        BUILD_DIR: docs/src/.vuepress/dist/
